spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seriesdb
    username: root
    password: 

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

 